### ISSUE TITLE
Make messages optional

### ISSUE THREAD

**Issue by dholm** [bastibe/annotate.el#10]
Would you consider adding a debug option that enables/disables the messages for `annotate.el`?  It would make the module be more transparent when enabled.

For instance, I prefer seeing the path to the file I just saved the buffer to on `C-x C-s` rather than "Annotations saved.".

**Comment by bastibe** [comment]
Sure, I can do that!

**Comment by dholm** [comment]
Cool, thanks!

**Comment by bastibe** [comment]
This is implemented in 0.2.3 now. Just `(setq annotate-use-messages nil)`, and annotate.el won't bother you again.

**Comment by dholm** [comment]
@bastibe Awesome, thank you!
