### ISSUE TITLE
Conflict with form-feed.el

### ISSUE THREAD

**Issue by mmauger** [bastibe/annotate.el#11]
Once form-feed-mode (https://github.com/wasamasa/form-feed) is enabled, the annotation text on the right disappear.  Not sure who is not playing nice, but one of you are getting in the way of the other.

**Comment by bastibe** [comment]
I think both modes use the same technique for display: Changing the `display` property of the linefeed character. I don't know of any way to allow multiple `display` properties.

I suppose one could use overlays instead, but they are supposedly slow if used often, and have other properties that make them less nice to work with.

If you know a solution to this, I would be very interested indeed!

**Comment by mmauger** [comment]
I know that they are both using display properties but I have files with no ^L in them so form-feed-mode is doing nothing to the file, but it still hides the annotations.  This probably needs more debugging to see who is misbehaving.  I'll log an issue with form-feed-mode as well to report that they are altering the appearance even when no ^L's are present.

**Comment by bastibe** [comment]
I have looked into this quite thoroughly now, and could not figure it out. When `form-feed` is enabled, my text properties (that's the annotations at the end of the line) vanish. I have no idea why, or how to circumvent this.

It did lead me to an interesting idea on how to improve annotate mode, though, so I might find a solution to this yet.

**Comment by bastibe** [comment]
I'm closing this for now, since I don't see any way of fixing this with the current code base. The incompatibility is noted in the README.
