### ISSUE TITLE
[news] Annotate.el landed in NonGNU ELPA

### ISSUE THREAD

**Issue by cage2** [bastibe/annotate.el#121]
Hi @bastibe !

Annotate.el has been included in NonGNU ELPA!

https://elpa.nongnu.org/

https://git.savannah.gnu.org/cgit/emacs/nongnu.git/commit/?id=84e7ce062d8c5685d43d4808941a2bac399775e2

And, also important, along the process a few interesting ideas, and a patch arose! :+1: 

I will add, in the next days, the features proposed as issue report here so that we can discuss them. Also will apply the patch to my fork so that we can have a pull request that could be easily studied and modified/applied.

Bye!
C. 

EDIT: for reference here is the relevant discussion on emacs-devel mailing list:

https://lists.gnu.org/archive/html/emacs-devel/2022-01/msg01826.html

**Comment by bastibe** [comment]
Thank you for getting annotate.el published on NonGNU ELPA! That's fantastic news!

For what it's worth, I'd be happy to sign over my copyright and publish annotate.el on ELPA. But there has been at least one other contributor whom we would have to ask as well. In the end, I don't think the choice of repository makes any tangible difference to most users, so it is probably not worth the effort.

**Comment by cage2** [comment]
Hi Bastian!

> Thank you for getting annotate.el published on NonGNU ELPA! That's fantastic news!

My pleasure! I am happy too! :)

>  For what  it's worth, I'd  be happy to  sign over my  copyright and
> publish annotate.el on  ELPA. But there has been at  least one other
> contributor whom we would  have to ask as well. In  the end, I don't
> think the choice of repository makes any tangible difference to most
> users, so it is probably not worth the effort.

I agree that  now that you can install annotate  using the same method
as the ELPA packages there is no pressure to do so!

I hope  tomorrow i could apply  the patch and starting  the discussion
about using margin as space for  annotation text (an intriguing idea i
would like to explore!).

Bye!
C.
