### ISSUE TITLE
[new feature] Using a file 'FILENAME.notes' to hold the annotations of file 'FILENAME'

### ISSUE THREAD

**Issue by cage2** [bastibe/annotate.el#124]
This is a big change, as means get rid of the database.

Comments welcome!
Bye!
C.

**Comment by bastibe** [comment]
Sounds reasonable and useful! At least, as an option. I think there are use cases for both behaviors.

**Comment by cage2** [comment]
Hi!

> Sounds reasonable and useful! At least,  as an option. I think there
> are use cases for both behaviors.

Sure! I also remember a friend  of mine asking for such modification!
:) I  wonder where to  graft this feature  in the code,  but definitely
nothing impossible!

Bye!
C.
