### ISSUE TITLE
annotate-delete-annotation doesn't delete annotation

### ISSUE THREAD

**Issue by anildigital** [bastibe/annotate.el#126]
annotate-delete-annotation doesn't delete annotation. I can see entry in `annotations` file as is.

**Comment by cage2** [comment]
Hi @anildigital!

Yes that command is actually broken, but there are good news (hopefully!), #125 should fix this issue. By the way note that, when you run `annotate-delete-annotation` the annotations database file is modified only after the file is saved not just after the annotation is deleted using the command you mentioned above.

@bastibe  do you think can i merge #125?

Bye!
C.

**Comment by cage2** [comment]
Hi!

The patch in #125 has been merged, may i ask to check if the problem persisted?

Bye!
C.

**Comment by cage2** [comment]
Hi!

I am closing this issue after merging #125. Feel free to reopen if the problem persists.

By!
C.
