### ISSUE TITLE
Files with no annotations are listed in the annotations file

### ISSUE THREAD

**Issue by mmauger** [bastibe/annotate.el#13]
I have annotation-mode enabled in the prog-mode-hook.  As I update packages, the code needs to be read in to be byte compiled and I end up with an entry in the annotations file with that name.  If a file has no annotations it probably ought not appear in the annotations list.

**Comment by bastibe** [comment]
Is this a duplicate of #14? How are the two issues related?

**Comment by mmauger** [comment]
Not a duplicate and probably not related.

I have a lot of entries in my annotations file that only contain the file name key with no annotations afterwards.  As I open hundreds of files either explicitly or behind the scenes, I end up with a annotations file that is a few K in size listing every file opened but only one file actually has annotations.

**Comment by bastibe** [comment]
Oh, now I get it. That should be easy to fix.

**Comment by bastibe** [comment]
Should be fixed now.
