### ISSUE TITLE
annotate disables exchange-point-and-mark

### ISSUE THREAD

**Issue by rhstanton** [bastibe/annotate.el#131]
Normally, pressing C-x C-x (exchange-point-and-mark) right after pasting text in an Emacs buffer moves the cursor back to the beginning of the just-pasted text. If annotate-mode is active, the cursor just stays where it is.

**Comment by rhstanton** [comment]
Ignore this. I think the true culprit is elsewhere in my init.el file.

**Comment by cage2** [comment]
Hi @rhstanton !

TIL a new useful command! :)

Thanks!
C.
