### ISSUE TITLE
The file names in the annotation file have text properties

### ISSUE THREAD

**Issue by mmauger** [bastibe/annotate.el#14]
some of the files I use are accessed via TRAMP. The file name in the annotations file includes text properties as well as the name string.  The text properties ought to be stripped off when stored in the annotation file and any lookup comparison ought to only match the string portion and ignore properties.

**Comment by bastibe** [comment]
I don't quite understand the problem yet. Could you try to give an example of how this problem manifests itself?

**Comment by mmauger** [comment]
If a file is remote, (buffer-file-name) returns a string with text properties like (obviously obfuscated):

  #("/scp:xyz-remhost:/users/mmauger/proj/abcdef/ghijklmnopqrstuv.sql" 1 4 (tramp-default t) 5 16 (escaped t) 32 36 (escaped t) 36 64 (escaped t))

This is a legit file name but it contains info to assist TRAMP in parsing the string more efficiently. Essentially you need to wrap (buffer-file-name) with (substring-no-properties <string>) to strip the properties. 

The result from above becomes:
    "/scp:xyz-remhost:/users/mmauger/proj/abcdef/ghijklmnopqrstuv.sql"

**Comment by bastibe** [comment]
Should be fixed in 0.3.5
