### ISSUE TITLE
Is it possible to change the color of the underline, and the background color of the note text?

### ISSUE THREAD

**Issue by Prague2049** [bastibe/annotate.el#145]
Is it possible to change the color of the underline, and the background color of the note text?

**Comment by bastibe** [comment]
You can customize the various faces used by annotate: https://github.com/bastibe/annotate.el/blob/master/annotate.el#L96

**Comment by cage2** [comment]
Hi @Prague2049 

Something in the code has changed from you message, now to change the theme of the annotations you need to modify the value of these two variables:

https://github.com/bastibe/annotate.el/blob/master/annotate.el#L96
https://github.com/bastibe/annotate.el/blob/master/annotate.el#L101

Bye!
C.
