### ISSUE TITLE
how to create annotate file for each org file?

### ISSUE THREAD

**Issue by emacs25** [bastibe/annotate.el#148]
i have serveral org files to read,so i want to
create annotations file in a special directory.

for example,my org files are in ~/org and there
 is another directory ~/annotation

how to store all annotation files in ~/annotati
on with same file name?

```
~/org:
1.org
2.org
...

~/annotation:
1.annotation
2.annotation
...
```

**Comment by cage2** [comment]
Hi @emacs25 !

I think there is no ready to use solution for your workflow.

You can have an annotation database in the same directory of the annotated file see:

https://github.com/bastibe/annotate.el#non-centralized-database

to have multiple databases in different directory you probably need to write a bit of elisp that uses: `annotate-switch-db`

https://github.com/bastibe/annotate.el#annotate-switch-db

Bye!
C.

**Comment by emacs25** [comment]
okay,i will read these codes clearly,thanks very much!
