### ISSUE TITLE
Feature request: navigate between annotations

### ISSUE THREAD

**Issue by mmauger** [bastibe/annotate.el#15]
Having a annotate-next and annotate-previous functions would be helpful.  Assigning them to keys would be very helpful: C-c C-n and C-c C-p, or create an annotate keymap

**Comment by bastibe** [comment]
Very good idea! I'll look into this next week.

If you want to have a stab at it, I'd be very happy about that, too!

**Comment by bastibe** [comment]
Implemented in the latest version.
