### ISSUE TITLE
could not edit annotations using "C-c C-a"

### ISSUE THREAD

**Issue by emacs-newer** [bastibe/annotate.el#152]
when i move cursor to highlight text,"C-c C-a" just opens minibuffer to prompt new annotation instead of modifying the exsiting annotations.

and could it popup a temp buffer to edit current annotation and kill the buffer automatically after finished?

**Comment by cage2** [comment]
Hi @emacs-newer !

This is really strange, i propose to wait the merging of #151 and  test again for this bug.

Bye!
C.

**Comment by emacs-newer** [comment]
thanks

i also try it serveral times but no editable content to show.

and i disable minibuffer resize and i am not sure is it the problem

**Comment by cage2** [comment]
Hi @emacs-newer !

The patch in #151 has been merged, please can you check if the bug still persists?

Bye!
C.

**Comment by emacs-newer** [comment]
great,works very well.
