### ISSUE TITLE
can annotation be wrapped?

### ISSUE THREAD

**Issue by emacs-newer** [bastibe/annotate.el#153]
my annotation for a highlight annotation is like this:
```
1. annotation one;2. annotation two;3. annotation three.
```
is it possible to wrap after each ";"?
```
1. annotation one;
2. annotation two;
3. annotation three.
........
```

**Comment by cage2** [comment]
Hi!

You can add a newline in an annotation using the command 'C-q' followed by 'C-j'.

So, for example:


1. annotation line one; 'C-Q C-j"

will write the rest of the annotation's text in a new line.

Hope this helps. :)

Bye!
C.

**Comment by emacs-newer** [comment]
works and thanks
