### ISSUE TITLE
Zero length annotation targets are not visible

### ISSUE THREAD

**Issue by mmauger** [bastibe/annotate.el#17]
Type C-SPC C-c C-a and you will get an annotation with the same start and end point (i.e., a zero length range). The annotation text is visible on the right, but there is no identification of the annotation itself.  Zero length ranges should be handled like a single character location so that they are visible.

**Comment by bastibe** [comment]
Interesting. I'm not quite sure how to handle these. Do you have any application for zero-length annotations? If not, I would be inclined to simply disallow them.

**Comment by mmauger** [comment]
I have no need for them but they easily appear, I'd suggest treating them like the no region case, just add 1 to the endpoint:

in annotate-bounds:
-             ((region-active-p) (region-end))
-            ((region-active-p) (+ (if (= (region-beginning) (region-end)) 1 0) (region-end)))

It may require additional changes but that is the obvious change...

**Comment by bastibe** [comment]
This is fixed in 0.3.2. Annotate now respects `use-empty-active-region`. If this is `t`, you can annotate empty regions. If not (the default), it will behave as if no region was active.
