### ISSUE TITLE
cl package required at runtime

### ISSUE THREAD

**Issue by mmauger** [bastibe/annotate.el#18]
When byte-compiled the warning above is issued.

Use `(eval-when-compile (require 'cl))` rather than just `(require 'cl)`

Also, use `cl-remove-if` rather than `remove-if`.

This will work with any version of Emacs that supports ELPA/MELPA packages.

**Comment by bastibe** [comment]
OK, I believe I fixed all `cl`-related errors. Note that `(eval-when-compile (require 'cl))` would only work if I did only use cl macros.

I now require `cl-lib` instead. The downside of this is that this requires Emacs 24. I don't know if that is really a good trade-off.
