### ISSUE TITLE
Key assignments

### ISSUE THREAD

**Issue by mmauger** [bastibe/annotate.el#19]
Emacs has rules for the assignment of keyboard sequences that clash with the assignments used in annotate.

Minor modes can define `C-c <punct>`, which may activate a keymap.  So, `C-c = C-a` would execute `annotate-annotate` etc.

> Minor modes may bind commands to key sequences consisting of C-c followed by a 
> punctuation character. However, sequences consisting of C-c followed by one of {}<>:;, 
> or a control character or digit, are reserved for major modes. Also, C-c letter is 
> reserved for users. See Key Binding Conventions. 
> -- [Emacs Elisp Ref, 22.3.2 Keymaps and Minor Modes](https://www.gnu.org/software/emacs/manual/html_node/elisp/Keymaps-and-Minor-Modes.html#Keymaps-and-Minor-Modes)

See [Emacs Ref, Keys assigned](https://www.gnu.org/software/emacs/manual/html_node/emacs/Key-Index.html#Key-Index_ky_letter-C) for existing key assignments

**Comment by bastibe** [comment]
Thank you for the hint! How about `C-c [` and `C-c ]` for next/previous annotations. Does that sound good? I would like to keep `C-c C-a`, since adding annotations is the most important feature of annotate, and should be placed prominently.

**Comment by bastibe** [comment]
OK, I changed the next/previous key bindings in the latest version
