### ISSUE TITLE
Annotations not displaying (wrong-type-argument overlayp nil)

### ISSUE THREAD

**Issue by jmacdonagh** [bastibe/annotate.el#21]
I've tried annotate.el on two different builds of Emacs and each time I get the error message:

> Fontifying block...(wrong-type-argument overlayp nil)

The two build I tried were:
1. OS X Homebrew emacs-mac-port 24.5.1 (as described in https://github.com/syl20bnr/spacemacs#os-x)
2. Emacs 24.5.1 built from source running on Ubuntu 14.04

In both cases I started from a clean Emacs start (emacs -Q), `load-file annotations.el` `annotate-mode` `C-c C-a test RET`. The message immediately appears and the symbol my cursor was at has an underline.

Annotations are being saved, just not displayed.

Any idea? Thanks!

**Comment by jmacdonagh** [comment]
I forgot to mention. For both builds I tried annotating a regular file, not the _scratch_ buffer or anything like that.

**Comment by bastibe** [comment]
Interesting. Is this specific to the emacs-mac-port? Did you try installing _annotate.el_ through _package.el_? (this would hint at an autoload issue)

Can you try to temporarily rename your `˜/.annotations`? Maybe that file got corrupted somehow.

**Comment by jmacdonagh** [comment]
Originally I found this bug when trying it out in spacemacs, which did install via `package-install`. However, this same thing did happen on a fresh build of 24.5.1 on Ubuntu 14.04 (`./configure` `make` `sudo make install`). For both builds I tried running with -Q and doing a `load-file` to reduce the complexities.

Later tonight I will try again, ensuring `~/.annotations` has been removed (I haven't made any real annotations yet).

Thanks!

**Comment by bastibe** [comment]
So far, I can not reproduce this on Emacs 24.4.1 on Mac and Linux.

**Comment by jmacdonagh** [comment]
Maybe its a 24.5.1 only issue?

**Comment by jmacdonagh** [comment]
This is strange. It's not working with 24.4.1 for me.
1. I built Emacs 24.4.1 from source for Ubuntu 14.04.
2. I moved `~/.emacs.d` away and removed the (non-existent) `~/.annotations`.
3. I `mkdir .emacs.d` and created `init.el` and set the contents to:

> (setq package-archives '(("marmalade" . "https://marmalade-repo.org/packages/")
>                        ("melpa" . "http://melpa.org/packages/"))
1. Started up Emacs, `M-x package-refresh-contents RET` `M-x package-install annotations RET` `C-x C-f ~/.emacs.d/init.el RET` `M-x annotate-mode RET` `C-x C-a test RET`. Got the same error.

Let me try with the built-in Ubuntu Emacs.

**Comment by jmacdonagh** [comment]
Works with the built-in Emacs. I must be missing some `./configure` option for my custom builds. I'll try to look into this further. Sorry, I should have checked the built-in Emacs first before reporting. Thanks for the quick reply!

**Comment by bastibe** [comment]
OK, if I have time this weekend, I'll try to look into this issue with the emacs-mac-port. Maybe there's an easy workaround.

Thank you for investigating.

**Comment by jmacdonagh** [comment]
I'll re-open this then if you're going to investigate, just in case others find this. I looked through the ./configure options and didn't notice anything I missed that might cause this.

By the way, the bug appears to have been introduced with 785b5aea7fd45fe914c592eb40208b0ad5ae0228 (which, as you might imagine, is when you rewrote the display engine :) ). If I use the previous commit then annotations display fine without error.

**Comment by bastibe** [comment]
I tried this again with the [Emacs Mac Port](https://github.com/railwaycat/homebrew-emacsmacport) and [Emacs For Mac OS X](http://emacsformacosx.com/), both at version 24.5.1, and still can't reproduce the bug. Annotate.el seems to work fine on both Emacsens.

**Comment by bastibe** [comment]
I fixed a few bugs in the latest release (0.4.2). Among these there was one that matches the error message you were getting. Can you check if your issue is fixed?

**Comment by jmacdonagh** [comment]
Just checked, the issue is fixed! I did a `git bisect` and discovered the bug was fixed on commit f31eddb52387e3b9f2bbcc189283e57c8b008551 (which, now that I look at the commit message, is obvious). I'm currently using the latest in your master branch to fix some of the newline bugs I noticed as well.

Thanks for all the great work!
