### ISSUE TITLE
fix integrate-annotations for HTML comments

### ISSUE THREAD

**Issue by bastibe** [bastibe/annotate.el#33]
Currently, it does not know about the length of the comment character, and it does not close the comments.

**Comment by cage2** [comment]
Hi!

I think i added this feature (some testing required though).

https://notabug.org/cage/annotate.el 

branch: close-comment

Bye!
C.

**Comment by bastibe** [comment]
Thank you! Could you upload your changes as a pull request on Github? That would make it much easier for me to review.

**Comment by cage2** [comment]
Hello bastibe!

I think this issue could be closed.

Bye!
C.
