### ISSUE TITLE
Prevent undo tree

### ISSUE THREAD

**Issue by futurist** [bastibe/annotate.el#36]
Cannot undo with commit f089237 (and not tested previous commits...)

The undo-tree-undo shows:

> user-error: No further undo information [36 times]

And `M-x undo` shows:

> primitive-undo: Unrecognized entry in undo list undo-tree-canary [2 times]

**Comment by bastibe** [comment]
Annotations are explicitly not part of the undo-history, as they don't change the file contents. But all your other edits should be unaffected from annotate.el.

Can you explain exactly what you are doing, what you expect to happen, and what does happen?
