### ISSUE TITLE
Autoloading custom variables acts as hardcoding

### ISSUE THREAD

**Issue by rnkn** [bastibe/annotate.el#37]
Hello again,

Similar to https://github.com/bastibe/org-journal/issues/87 the following autoload cookies act as hardcoded variable values:

https://github.com/bastibe/annotate.el/blob/f08923762fb851edb292ba4d3ebb07bea025f83d/annotate.el#L71-L111

I see you use a lot of autoloading... you really only need to autoload functions that the user would call *before* loading your mode, so e.g. really only:

https://github.com/bastibe/annotate.el/blob/f08923762fb851edb292ba4d3ebb07bea025f83d/annotate.el#L56-L65

All other autoload cookie comments can safely be removed 😎

**Comment by bastibe** [comment]
Thank you again! I implemented this in dedbd9e5d5286f1ca8ad73e489d408a20f06156c
