### ISSUE TITLE
Integrate with no-littering

### ISSUE THREAD

**Issue by Fuco1** [bastibe/annotate.el#38]
https://github.com/emacscollective/no-littering is a package to manage files created/saved by packages to have them in a unified location. This makes the clutter in home/emacs directories much more managable.

**Comment by bastibe** [comment]
You can customize `annotate-file` to point to your preferred location, if the default does not suit you. However, annotate.el has existing users, and I can't change the default without breaking their existing annotations.

**Comment by Fuco1** [comment]
Hm, no.  This works the other way round.  We would add an entry to no-littering's database for this package. Then the users of *that* package would get consistent locations.  No change is required in this package.

**Comment by bastibe** [comment]
So you are saying that I should write a pull request to no-littering and set `annotate-file`, there?

**Comment by Fuco1** [comment]
Not that you should do it, just someone.  I might do it if I find some time, this is just a reminder mostly.

**Comment by cage2** [comment]
Hello!
Support for annotate.el has been included in no-littering

Thank you!
C.
