### ISSUE TITLE
Issues with displaying annotations out of visible range

### ISSUE THREAD

**Issue by pascalfleury** [bastibe/annotate.el#39]
Hi !
I just installed this package from melpa, and it gets emacs into a strange state.

when I add an annotation, and the current buffer does not show enough columns (e.g. my view has 62 colums visible), then adding an annotation fails with this message (from *Message* buffer):
Error during redisplay: (jit-lock-function 3042) signaled (args-out-of-range "where it all started" 0 -22)

Note how 85-62 = 23, and we get -22 (I guess it's zero-based).

And the annotation does not show. If I resize then buffer to make space, it displays it, so it gets stored.

When annotations are added when there is enough space, and then the buffer is resized, the annotation flows fine. Just at creation time it gets confused.

**Comment by pascalfleury** [comment]
note that the 'where it all started' is my annotation's text.

**Comment by bastibe** [comment]
Do you want to try and look into the code to find the issue? I probably won't have time to look into it in the near future.

**Comment by pascalfleury** [comment]
Hi Bastian,

I'm afraid, but my Lisp-foo is too basic for this... I basically know how
to set customvars, and use-package and otherwise cut/paste example code,
but no much else :-)

--paf

**Comment by bastibe** [comment]
OK, no problem. If I don't get to it in time, and it is still important for you, please ping me again on this thread. But I'm afraid the next few weeks are very full on my end.

Anyway, thank you very much for the bug report.

**Comment by pascalfleury** [comment]
No worries. Also this way, people will see the report.
I'll file a feature request as well for another thing, with the same
absence of urgency:-)

Have a nice day, and thanks for this nice package.

-- paf

Le lun. 5 nov. 2018 à 13:18, Bastian Bechtold <notifications@github.com> a
écrit :

**Comment by mokrates** [comment]
I have the same problem:

*Messages*
Fontifying block...(args-out-of-range  0 -1) [2 times]
Error during redisplay: (jit-lock-function 1) signaled (args-out-of-range "" 0 -1)
user-error: Minibuffer window is not active
delete-backward-char: Text is read-only
QuitError during redisplay: (jit-lock-function 1) signaled (args-out-of-range "" 0 -1)
Error during redisplay: (jit-lock-function 1) signaled (args-out-of-range "" 0 -1)
QuitError during redisplay: (jit-lock-function 1) signaled (args-out-of-range "" 0 -1)

If I resize the whole emacs around, then at some point emacs crashes and lets itself kill only by kill -9.
I really wanted to use this!

cool plugin though!

mo

**Comment by bastibe** [comment]
If you want to take a stab at this, I'd be very happy to merge a pull request. I don't have the time to do it myself at this point, though.

**Comment by cage2** [comment]
Hi!

I tried to address both issues on:

https://notabug.org/cage/annotate.el

branch: fix-out-of-range

Please consider take a look on it and maybe merging. :)

Also, please, take in account that this is my first elisp code so very likely i have broken some stylistic/efficiency rule (the indentation of inner function seems weird to me, for example) so be patient :)

Bye!
C.

**Comment by cage2** [comment]
Hello!

Also i fixed a couple of other bugs that i think i have spotted; you can review the changes on the same url i wrote in my previous message.

Bye!
C.

**Comment by bastibe** [comment]
Thank you for your code. Could you upload them to Github as a pull request? That would make it much easier for me to review.

**Comment by cage2** [comment]
On Fri, Sep 06, 2019 at 02:39:48AM -0700, Bastian Bechtold wrote:
> Thank you for your code.

You're welcome!

> Could you upload  them to Github as a pull  request? That would make
> it much easier for me to review.

Sure! :) I just submitted a PR.

Bye!
C.
