### ISSUE TITLE
Not strictly a code issue

### ISSUE THREAD

**Issue by cage2** [bastibe/annotate.el#65]
Hi Bastian,

i know this is not exactly a code issue but issue is made by human being so...

Because i do not know a simple way to get in touch with you i am using this method.

My question is simple. Are you fine? 

Bye!
C.

**Comment by bastibe** [comment]
Hi Cage,

I am healthy. Am I fine? That question hit me at a strange moment. Just a few moments earlier I had finally, finally, sent off my dissertation to my friends to review.

There is so much anxiety and stress and, well, depression, bundled up in that PDF file. The last few months were tough. I honestly don't know what to feel, yet.

Is there a specific reason you were asking? Are you fine? I hope you are doing well. You seem to be a nice person.

Feel free to contact me via email (my email address is in every commit I make).

Thank you for caring,
Bastian

**Comment by cage2** [comment]
OK, i think this "issue" can be successfully closed. ;-)

PS: also: hello randomwangran! :wave:
