### ISSUE TITLE
Tag current release for inclusion in melpa stable

### ISSUE THREAD

**Issue by cage2** [bastibe/annotate.el#66]
Hi Bastibe!

As about three months have passed without pull requests i was thinking that the current version  (0.6.2) of the library could be tagged to be included in melpa stable, what do you think about that? Is is a good idea? Should we upgrade the release to a higher number (like 0.7.0)? 

Bye!
C.

**Comment by bastibe** [comment]
Yes, I agree!

Do you want to create a pull request that bumps the version number and tags 0.7.0?

**Comment by cage2** [comment]
Hi Bastian!

i just added a pull request: #67 

This is going to be the first time in my life that my code will go in MELPA stable! :-)

Bye!
C.

**Comment by bastibe** [comment]
Congratulations! You improved this project by leaps and bounds! Thank you!

I just pushed the tag into git, and melpa-stable will usually update within the next 24 h or so.

**Comment by cage2** [comment]
Hi Bastian!

It was a pleasure to contribute to this project so far and i intend to continue to contribute or improve it in the future.

Thank you for helping me in this journey!

Bye!
C.
