### ISSUE TITLE
Annotate not visible in MELPA package manager?

### ISSUE THREAD

**Issue by ReneFroger** [bastibe/annotate.el#7]
Hi Bastibe, it's me again! 

Thanks for sharing this package! Could this perhaps be listed on MELPA?

Thanks in advance!

**Comment by bastibe** [comment]
It is listed on [Melpa](http://melpa.org/#/annotate), [Melpa Stable](http://stable.melpa.org/#/annotate), and [Marmalade](https://marmalade-repo.org/packages/annotate).

Maybe you need to `package-refresh-contents`?

**Comment by ReneFroger** [comment]
You're right, my fault. Thanks for the answer!
