### ISSUE TITLE
multiple annotations feature requests

### ISSUE THREAD

**Issue by llcc** [bastibe/annotate.el#8]
@bastibe Thanks for helping me fix the last issue.

Here i would like to ask if you can add one new feature to your package:
As described in my situation, i am using `visual-line-mode` so always be one paragraph one logical line. In this situation, there will be some demands that annotate several parts of the paragraph, respectively. But since now, it looks like that only on annotation is supported in your package.

Of course, if multiple annotations can be implemented, various text properties should also be considered in my opinion, that is, underlining words and their annotation should have same text properties, but differ with others in same paragraph.

Thanks ahead of time. I will be really appreciate if you can make it possible. I can help you to test at anytime, just please give me a notice!.

**Comment by bastibe** [comment]
This would be very useful. Another use-case I did not think of.

This will require some re-architecting, though. 

I could introduce a setting for where annotations will be placed: Either on the end of the line, or above the line, or below the line. Depending on the kind of annotations you are writing, this will give you enough space to write them.

Then, I could give multiple annotations different colors.

Would this solve your problem, or can you think of a better way of doing this?

**Comment by llcc** [comment]
The way you were describing are absolutely matching my demand.
 I am expecting your good news!

**Comment by bastibe** [comment]
Just a heads-up, this will probably take a while.

**Comment by bastibe** [comment]
This is the next big thing I want to tackle, but I'll be on vacation for a while and won't have access to computers. Expect progress in mid September.

**Comment by bastibe** [comment]
There has been progress: You can now have several annotations per line, and they will all be shown one after another, each on it's own line. 

For now, all annotations are still shown in the right margin, though.

I had to re-architect the whole display engine to do this, so I'll wait a few days to weed out any bugs that came with this change before adding more features.

The next thing I want to tackle is to make the position of annotations customizable. Please head over to #20 to see progress on this.
