### ISSUE TITLE
Automatically expand overlapping annotation

### ISSUE THREAD

**Issue by xeruf** [bastibe/annotate.el#83]
I accidentally placed my annotation on only a few words, but I intended to annotate the whole line:

![image](https://user-images.githubusercontent.com/13354331/97117676-9d85d080-1705-11eb-9f9e-88f5bb57ab3f.png)

When selecting the whole line and pressing `C-c C-a`, I get the following error:

![image](https://user-images.githubusercontent.com/13354331/97117665-7d561180-1705-11eb-92d7-fe5ee4d07021.png)

I would have expected it to widen the annotation to my selection and then simply let me edit the text.
It seems with the current behavior I have to copy the annotation text, delete the annotation and then create it again...

**Comment by bastibe** [comment]
Great idea, actually, to widen the annotation instead of throwing an error.

**Comment by cage2** [comment]
On Mon, Oct 26, 2020 at 01:54:29AM -0700, Bastian Bechtold wrote:

Hi Bastian!

> Great idea, actually, to widen the annotation instead of throwing an error.

I agree that this is a good idea and that i would like to try to implement! :)

Bye!
C.

**Comment by cage2** [comment]
Hi @xerus2000 !

I have just filed a PR  (#87)  that should address your issue, i wonder if i has been able to deal with all the cases when an annotation can overwrite others. Would be great if you could check this branch and makes some minimal testing. Could you?

Bye and thanks in advance!
C.

**Comment by xeruf** [comment]
I'll see, currently busy with other stuff, and annotate is kinda not serving me that well since I often edit files after annotating them ;)

**Comment by cage2** [comment]
On Wed, Dec 02, 2020 at 12:09:23PM -0800, Janek wrote:

Hi!

> I'll see, currently busy with other stuff, and annotate is kinda not
> serving me that well since I  often edit files after annotating them
> ;)

No problem! take your time and thank you anyway! :)

Bye!
C.
