### ISSUE TITLE
support ~/ 

### ISSUE THREAD

**Issue by randomwangran** [bastibe/annotate.el#89]
If the file path in `annotations` is like: `"/home/username/.emacs.d/elpa/annotate-20201216.1526/annotate.el"`, everything is good.

But if manually change the path like `"~/.emacs.d/elpa/annotate-20201216.1526/annotate.el"`

After opening `annotate.el`, no annotations will be displayed.

It would be nice to expand the file name. I believe this will be good for multi-computers user.

**Comment by cage2** [comment]
On Wed, Dec 16, 2020 at 08:57:11AM -0800, randomwangran wrote:

Hi randomwangran!

This is the simplest  of your report so i am  start replying with this
one first! ;-)

> If the file path in `annotations` is like: `"/home/username/.emacs.d/elpa/annotate-20201216.1526/annotate.el"`, everything is good.
>
> But if manually change the path like `"~/.emacs.d/elpa/annotate-20201216.1526/annotate.el"`
>
> After opening `annotate.el`, no annotations will be displayed.
>
> It would be nice to expand the file name. I believe this will be good for multi-computers user.

Seems interesting! If i understand  correctly what you suggest here is
to apply the function:

'expand-file-name'

https://www.gnu.org/software/emacs/manual/html_node/elisp/File-Name-Expansion.html#File-Name-Expansion

when reading the path from each record of the databases of annotation so that, for example:

~/foo -> /home/username/foo

and, symmetrically, apply:

'abbreviate-file-name'

https://www.gnu.org/software/emacs/manual/html_node/elisp/Directory-Names.html#Directory-Names

before saving the path component of a record into the database.

Is this correct?

I wonder if this is backward compatible with existing database format, i think it was.

Bye!
C.

**Comment by randomwangran** [comment]
Hi @cage2 You are right. 

If you have free time, please consider this support. I believe this is
a useful feature for users.

At the mean time, I am also studying this `annotate.el` to see if I
can do a compatible modification to it, but I am not sure when I can
finish it.

**Comment by cage2** [comment]
On Wed, Dec 16, 2020 at 04:54:18PM -0800, randomwangran wrote:
> Hi @cage2

Hi!

> You are right.

Good! :)

> If you have free time, please consider this support. I believe this is
> a useful feature for users.

I think this is  a good improvement and i would  be happy to implement
it  (also should  not be  too difficult ;-) and backward  compatible, the
latter is important).

> At the mean time, I am also studying this `annotate.el` to see if I
> can do a compatible modification to it, but I am not sure when I can
> finish it.

That is awesome!  Take  your time, this is not a race  and there is no
pressure to release. feel free to  ask for question and, mot important,
have fun! :)

Bye!
C.

**Comment by cage2** [comment]
Hi @randomwangran !

I have proposed a patch to implement the subject of this thread:

#92 

Please, can you take a look and tell me if it works?

Thank you very much for your help!
Bye!
C.

**Comment by randomwangran** [comment]
Perfect!

I've tested it and no problem.

Thanks for your effort! I close this issue but feel free to ask any question.

**Comment by cage2** [comment]
On Fri, Dec 18, 2020 at 11:45:55AM -0800, randomwangran wrote:

Hi!!

> Perfect!

🎉

> I've tested it and no problem.
>
> Thanks for your effort! I close this issue but feel free to ask any question.

Thank to you for suggesting that  feature! I would like to address the
problem about multiline notes and then asking for merging a bigger PR.

Or, if you  prefer, i could ask  the maintainer to merge  the PR (after
changed changelog files and version number).

I OK to you to wait for the other feature to be added before merging?

Bye!
C.

**Comment by randomwangran** [comment]
> I OK to you to wait for the other feature to be added before merging?

No problem. 

Thank you for making this happen @cage2 . Really appreciate it.

**Comment by cage2** [comment]
On Sat, Dec 19, 2020 at 06:44:30AM -0800, randomwangran wrote:
> > I OK to you to wait for the other feature to be added before merging?
>
> No problem.
>
> Thank you for making this happen @cage2 . Really appreciate it.

You are  welcome!  Fortunately  there was a  couple of  Emacs standard
functions that fitted exactly for this job! :)

Bye!
C.
