### ISSUE TITLE
render overlay as a whole block

### ISSUE THREAD

**Issue by randomwangran** [bastibe/annotate.el#90]
In a multi-lines note, there will be some blank lines. These
lines will not be render. This will make the notes a little bit
strange looking.

I have post two images to show what I mean.

The first one is the current state. The second one is the desired
state, which I use GIMP to render.

![image](https://user-images.githubusercontent.com/8197831/102387202-16830500-3f9e-11eb-8eed-a09e6de5fe4d.png)

![2020-12-16_124247](https://user-images.githubusercontent.com/8197831/102387505-75487e80-3f9e-11eb-9476-ce6a4f8f5ba6.png)

**Comment by cage2** [comment]
Hi @randomwangran !

A little question: you added manually (i mean with ^Q ^J two times) the linebreak in the annotation text, right?

Bye!
C.

**Comment by randomwangran** [comment]
I use this function to create new line: `default-indent-new-line`

```
M-j runs the command default-indent-new-line (found in global-map),
which is an interactive compiled Lisp function in ‘simple.el’.

It is bound to C-M-j, M-j.

(default-indent-new-line &optional SOFT)

Break line at point and indent.
If a comment syntax is defined, call ‘comment-line-break-function’.

The inserted newline is marked hard if variable ‘use-hard-newlines’ is true,
unless optional argument SOFT is non-nil.
```

Let me know if I am make it clear. Thank you.

**Comment by cage2** [comment]
On Thu, Dec 17, 2020 at 10:11:56AM -0800, randomwangran wrote:

Hi randomwangran!

I just pushed some modification to add this feature on the package.

May i ask to do some testing if it works fine or not?
Thanks in advance!
C.

NB: the rendering of the "box"  around the multiline annotated text is
slightly different  from the mock up you  posted as i do  not extend the
background  (i mean,  non printable  text with  "coral" as  background
color) to the border of the window (this could results in rendering if
the window  is shrunk even  by single  column), but just  enough to
wrap the text.

**Comment by randomwangran** [comment]
Hi @cage2 

c103381862f5124e5871c37282e67f3d2e0c588a works perfectly on my side!

> the rendering of the "box"  around the multiline annotated text is
slightly different 

Your version is the best. I mocked up just for illustration purpose. No worried about it.

Thanks for your effort!

**Comment by cage2** [comment]
On Sun, Dec 20, 2020 at 08:18:17AM -0800, randomwangran wrote:
> Hi @cage2

Hi!

> c103381862f5124e5871c37282e67f3d2e0c588a works perfectly on my side!
>
> > the rendering of the "box"  around the multiline annotated text is
> slightly different
>
> Your version is the best. I mocked up just for illustration purpose. No worried about it.
>
> Thanks for your effort!

My pleasure! :)

I think i  am more or less ready  to ask for merging, i  would like to
thank you in the NEWS file, are you OK with that? How should i mention
you, is "randomwangran" fine?

Bye!
C.

**Comment by randomwangran** [comment]
>I think i  am more or less ready  to ask for merging, i  would like to
thank you in the NEWS file, are you OK with that? How should i mention
you, is "randomwangran" fine?

I've done very little compare to you. It's my pleasure to be mentioned in the NEWS file. You can just call me "Ran". 

Thanks again for your contribution.

**Comment by cage2** [comment]
On Sun, Dec 20, 2020 at 10:44:59AM -0800, randomwangran wrote:

Hi!

> >I think i  am more or less ready  to ask for merging, i  would like to
> thank you in the NEWS file, are you OK with that? How should i mention
> you, is "randomwangran" fine?
>
> I've done very little compare to you.

You suggested  two new features  (and with good explanation,  i would
say) and helped  with testing. I think the mention  is well deserved!
:)

Bye!
C.
