### ISSUE TITLE
Symbol’s function definition is void: annotation when some text is selected in buffer

### ISSUE THREAD

**Issue by oatmealm** [bastibe/annotate.el#97]
When I select some text and invoke `annotate-annotate` I'm getting this error. Otherwise, things work as expected and the word at point gets used. Using doom, and package installed from MELPA. 

```
annotate-annotations-overlay-in-range: Symbol’s function definition is void: annotation
```

**Comment by cage2** [comment]
On Wed, Feb 03, 2021 at 03:26:38AM -0800, oatmealm wrote:

Hi!

> When I select  some text and invoke  `annotate-annotate` I'm getting
> this error. Otherwise, things work as expected and the word at point
> gets used. Using doom, and package installed from MELPA.

Unfortunately i can not  reproduce this bug. May i ask  if can you try
with the last version of the program pulled from this repository?

Bye!
C.

**Comment by oatmealm** [comment]
Same problem working on master... 1795816

**Comment by cage2** [comment]
Hi @oatmealm !

Sorry but i still can not reproduce the problem, can you instruct me how to get the bug?

- Should annotating any portion (region) of the buffer trigger the error? Or you get an error only when annotationg a specified portion of the buffer?
- Do you get the error when annotating the file for the first time?
- even if you get the error the buffer is annotated anyway?

Thank you!

PS: your report helped me to spot another bug in the code! :)

**Comment by oatmealm** [comment]
Should annotating any portion (region) of the buffer trigger the error? Or you get an error only when annotationg a specified portion of the buffer?

If there's a selection (I guess it's called transient highlight?) then it fails with the specified error. 

Do you get the error when annotating the file for the first time?

It happens always. The only way to add a note is to have the point somewhere and then invoke the command. It'd then selects the word near the pointer and highlights it. 

even if you get the error the buffer is annotated anyway?

No it doesn't annotate if I get the error. 

Glad to hear it helped you find another bug 🤓

**Comment by cage2** [comment]
On Fri, Feb 05, 2021 at 12:16:04PM -0800, oatmealm wrote:

Hi oatmealm!

[...]

>
> Glad to hear it helped you find another bug 🤓

Yes! An there is already a patch ready too! :)

But regarding your issue, given  you information, unfortunately i have
no chance to reproduce the bug.

Are  you sure  you are  running the  latest version  of the  software?
Something similar has happened recently.

I propose waiting for  the next version of the package  to go to MELPA
(non stable) so that we are sure  that we are running the same version
of annotate.

In the meanwhile i  am going to try to bisect the  repo (if i remember
how it works! ;-) ) trying to find a version that presents the bug you
reported.

What do you think?

Bye!
C.

**Comment by cage2** [comment]
On Fri, Feb 05, 2021 at 12:16:04PM -0800, oatmealm wrote:

Hi!

There is  a new  version of  the package on  MELPA, may  I ask  you to
install this version an try if the issue has gone?

Thank you!
C.

**Comment by dit7ya** [comment]
I am having the same problem, I just installed the problem from latest MELPA. Maybe it has something to do with Doom Emacs? Whenever something is selected I get this error - `annotate-annotations-overlay-in-range: Symbol’s function definition is void: annotation`.

**Comment by oatmealm** [comment]
Hi there!
Updated to current github version. Problem seems to persist.

In doom/straight notation: 

```
(package! annotate.el
  :recipe (:host github
           :repo "bastibe/annotate.el"))
```

**Comment by cage2** [comment]
On Fri, Mar 05, 2021 at 04:06:14AM -0800, oatmealm wrote:
> Hi there!

Hello everyone!

> Updated to current github version. Problem seems to persist.
>
> In doom/straight notation:
>
> ```
> (package! annotate.el
>   :recipe (:host github
>            :repo "bastibe/annotate.el"))
> ```

Given the  data available i  am inclined to  think that there  is some
conflict between Doom  and this package, do you think  would be useful
to forward this issue to Doom's maintainers?

Bye!
C.

**Comment by cage2** [comment]
Hi!

i forwarded this issue to Doom maintainers:

https://github.com/hlissner/doom-emacs/issues/4783

I hope we can get some help from them! :)

Bye!
C.

**Comment by cage2** [comment]
Hi @oatmealm and @dit7ya !

Please may i ask if someone of you could test #99 and check if this bug has gone?

Thanks in advance!
C.

**Comment by lululau** [comment]
> Hi @oatmealm and @dit7ya !
> 
> Please may i ask if someone of you could test #99 and check if this bug has gone?
> 
> Thanks in advance!
> C.

Tested #99 , it fixes this bug

**Comment by cage2** [comment]
On Tue, Mar 16, 2021 at 10:09:42PM -0700, FCP wrote:
> > Hi @oatmealm and @dit7ya !
> >
> > Please may i ask if someone of you could test #99 and check if this bug has gone?
> >
> > Thanks in advance!
> > C.
>
> Tested #99 , it fixes this bug

Many thanks for  you all! I just  pushed a few more commits  to the PR
and it will  be merged when ready  (usually in short time,  but we all
have a life out of the internet that reclaims its share! :-D).

Bye!
C.

**Comment by oatmealm** [comment]
Works for me as well. Thanks a lot!

**Comment by cage2** [comment]
On Thu, Mar 25, 2021 at 12:29:09AM -0700, oatmealm wrote:

Hi!

> Works for me as well.

Good! :)

> Thanks a lot!

Thanks  to you  for reporting  the bug,  likely i  never noticed  that
problem (and others, more or less related) if not for your report! :)

Bye!
C.
